### ISSUE TITLE
Shell?

### ISSUE THREAD

**Issue by zvezdochiot** [loh-tar/dupfi#1]
https://github.com/loh-tar/dupfi/blob/2d5485e19f8c20cc28c368a818b22c1ec9fa8609/dupfi#L1

:question: Maybe `#!/bin/sh`?

**Comment by loh-tar** [comment]
Well, /bin/sh is usually only a link to typically /bin/bash, but that's not sure. Using /bin/sh in scripts should be avoided.
It should work with bash fine. Other shell I didn't try.
See the comment below of the code. Using dash is a little bit faster, but that's not the main reason using it. It was just for fun, as extra challenge. :-)

**Comment by zvezdochiot** [comment]
```sh
$ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Mar  1  2012 /bin/sh -> dash
```

**Comment by loh-tar** [comment]
So, when you have dash installed, it should work.

**Comment by zvezdochiot** [comment]
30.05.2021 No actual.
